-- ============================================================
-- TimescaleDB Schema for PLC Data Collection
-- Database: neurosense | Schema: modbus
-- ============================================================

-- 0) 스키마 생성
DROP SCHEMA IF EXISTS modbus CASCADE;
CREATE SCHEMA IF NOT EXISTS modbus;

-- 1) TimescaleDB 확장 (이미 설치되어 있으면 무시)
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================
-- 2) 품질 코드 마스터
-- ============================================================
CREATE TABLE IF NOT EXISTS modbus.quality_code_master (
  quality_code SMALLINT PRIMARY KEY,
  quality_name TEXT NOT NULL,
  description  TEXT NULL
);

INSERT INTO modbus.quality_code_master (quality_code, quality_name, description)
VALUES
  (1, 'GOOD', '정상'),
  (2, 'UNCERTAIN', '불확실'),
  (3, 'BAD', '오류/통신불가')
ON CONFLICT (quality_code) DO NOTHING;

-- ============================================================
-- 3) PLC 마스터
-- ============================================================
CREATE TABLE IF NOT EXISTS modbus.plc_master (
  plc_id      SMALLINT PRIMARY KEY,
  name        TEXT NOT NULL,
  site        TEXT NULL,
  line        TEXT NULL,
  vendor      TEXT NULL,
  protocol    TEXT NOT NULL,
  timezone    TEXT NOT NULL DEFAULT 'Asia/Seoul',
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  conn_config JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_plc_master_site_line
  ON modbus.plc_master (site, line);

CREATE INDEX IF NOT EXISTS idx_plc_master_active
  ON modbus.plc_master (is_active);

CREATE INDEX IF NOT EXISTS idx_plc_master_conn_gin
  ON modbus.plc_master USING GIN (conn_config);

-- ============================================================
-- 4) TAG 마스터 (멀티 프로토콜)
-- 주의: "offset"은 PostgreSQL 예약어이므로 반드시 따옴표 사용
-- ============================================================
CREATE TABLE IF NOT EXISTS modbus.tag_master (
  tag_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plc_id            SMALLINT NOT NULL REFERENCES modbus.plc_master(plc_id),

  tag_name          TEXT NOT NULL,
  address           TEXT NOT NULL,
  address_meta      JSONB NOT NULL DEFAULT '{}'::jsonb,

  data_type         TEXT NOT NULL,
  byte_size         SMALLINT NOT NULL,
  collection_group  TEXT NOT NULL,

  scale             DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  "offset"          DOUBLE PRECISION NOT NULL DEFAULT 0.0,  -- 예약어: 따옴표 필수
  decimals          SMALLINT NULL,

  string_length     SMALLINT NULL,
  word_length       SMALLINT NULL,

  bool_true_value   INTEGER NULL,
  bool_false_value  INTEGER NULL,
  bool_invert       BOOLEAN NOT NULL DEFAULT FALSE,

  unit              TEXT NULL,
  description       TEXT NULL,

  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (plc_id, address),

  CHECK (byte_size > 0),
  CHECK (decimals IS NULL OR decimals >= 0),
  CHECK (string_length IS NULL OR string_length > 0),
  CHECK (word_length IS NULL OR word_length > 0)
);

CREATE INDEX IF NOT EXISTS idx_tag_master_plc_group
  ON modbus.tag_master (plc_id, collection_group);

CREATE INDEX IF NOT EXISTS idx_tag_master_plc_name
  ON modbus.tag_master (plc_id, tag_name);

CREATE INDEX IF NOT EXISTS idx_tag_master_addrmeta_gin
  ON modbus.tag_master USING GIN (address_meta);

-- 4-1) tag_master.updated_at 자동 갱신 트리거
CREATE OR REPLACE FUNCTION modbus.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tag_master_updated_at ON modbus.tag_master;
CREATE TRIGGER trg_tag_master_updated_at
BEFORE UPDATE ON modbus.tag_master
FOR EACH ROW EXECUTE FUNCTION modbus.set_updated_at();

-- ============================================================
-- 5) 이력 테이블 (TimescaleDB hypertable)
-- ============================================================
CREATE TABLE IF NOT EXISTS modbus.plc_data_integrated (
  source_time  TIMESTAMPTZ NOT NULL,
  server_time  TIMESTAMPTZ NOT NULL DEFAULT now(),
  plc_id       SMALLINT    NOT NULL,
  tag_id       INTEGER     NOT NULL,

  v_bool       BOOLEAN,
  v_byte       SMALLINT,
  v_int        INTEGER,
  v_bigint     BIGINT,
  v_float      DOUBLE PRECISION,
  v_text       TEXT,

  quality_code SMALLINT    NOT NULL DEFAULT 1
);

-- 5-1) Timescale hypertable 생성
SELECT create_hypertable('modbus.plc_data_integrated', 'server_time', if_not_exists => TRUE);

-- 5-2) FK (NOT VALID로 추가 - hypertable 호환)
-- 고성능 ingest가 필요하면 FK 제거 고려
ALTER TABLE modbus.plc_data_integrated
  ADD CONSTRAINT fk_plc_data_plc
  FOREIGN KEY (plc_id) REFERENCES modbus.plc_master(plc_id)
  NOT VALID;

ALTER TABLE modbus.plc_data_integrated
  ADD CONSTRAINT fk_plc_data_tag
  FOREIGN KEY (tag_id) REFERENCES modbus.tag_master(tag_id)
  NOT VALID;

ALTER TABLE modbus.plc_data_integrated
  ADD CONSTRAINT fk_plc_data_quality
  FOREIGN KEY (quality_code) REFERENCES modbus.quality_code_master(quality_code)
  NOT VALID;

-- 5-3) 인덱스
CREATE INDEX IF NOT EXISTS idx_plc_data_plc_tag_time
  ON modbus.plc_data_integrated (plc_id, tag_id, server_time DESC);

CREATE INDEX IF NOT EXISTS idx_plc_data_quality_time
  ON modbus.plc_data_integrated (quality_code, server_time DESC);

-- ============================================================
-- 6) 최신값 테이블 (tag_latest)
-- ============================================================
CREATE TABLE IF NOT EXISTS modbus.tag_latest (
  plc_id       SMALLINT    NOT NULL,
  tag_id       INTEGER     NOT NULL,

  source_time  TIMESTAMPTZ NOT NULL,
  server_time  TIMESTAMPTZ NOT NULL,
  quality_code SMALLINT    NOT NULL DEFAULT 1,

  v_bool       BOOLEAN,
  v_byte       SMALLINT,
  v_int        INTEGER,
  v_bigint     BIGINT,
  v_float      DOUBLE PRECISION,
  v_text       TEXT,

  PRIMARY KEY (plc_id, tag_id)
);

ALTER TABLE modbus.tag_latest
  ADD CONSTRAINT fk_tag_latest_plc
  FOREIGN KEY (plc_id) REFERENCES modbus.plc_master(plc_id);

ALTER TABLE modbus.tag_latest
  ADD CONSTRAINT fk_tag_latest_tag
  FOREIGN KEY (tag_id) REFERENCES modbus.tag_master(tag_id);

ALTER TABLE modbus.tag_latest
  ADD CONSTRAINT fk_tag_latest_quality
  FOREIGN KEY (quality_code) REFERENCES modbus.quality_code_master(quality_code);

CREATE INDEX IF NOT EXISTS idx_tag_latest_time
  ON modbus.tag_latest (server_time DESC);

-- ============================================================
-- 7) VIEW: 최신값 + 태그 메타 조인
-- ============================================================
CREATE OR REPLACE VIEW modbus.v_tag_latest AS
SELECT
  tl.plc_id,
  pm.name AS plc_name,
  pm.site,
  pm.line,

  tl.tag_id,
  tm.tag_name,
  tm.address,
  tm.data_type,
  tm.unit,
  tm.collection_group,
  tm.scale,
  tm."offset",  -- 예약어: 따옴표 필수
  tm.decimals,
  tm.string_length,

  tl.source_time,
  tl.server_time,
  tl.quality_code,
  q.quality_name,

  tl.v_bool,
  tl.v_byte,
  tl.v_int,
  tl.v_bigint,
  tl.v_float,
  tl.v_text
FROM modbus.tag_latest tl
JOIN modbus.tag_master tm ON tm.tag_id = tl.tag_id
JOIN modbus.plc_master pm ON pm.plc_id = tl.plc_id
JOIN modbus.quality_code_master q ON q.quality_code = tl.quality_code;

-- ============================================================
-- 완료
-- ============================================================
